### ISSUE TITLE
Cuda not detected

### ISSUE THREAD

**Issue by Yamenalbadin** [colmap/colmap#624]
I'm on a mac High Sierra with NVIDIA GTX 970 and ATI Radeon HD 2600. I have CUDA 10.0 installed and the latest Colmap 3.6-dev.2 when I try to make a dense reconstruction I get the message Dense stereo reconstruction requires CUDA, which is not available on your system. I tried deleting and reinstalling Colmap but it didn't work. I only have one version of CUDA installed.
what can I do?

**Comment by silence401** [comment]
I have the same problem with ubuntu18.04 and cuda10. I change the cuda10 to cuda9 but still not work

**Comment by silence401** [comment]
> I have the same problem with ubuntu18.04 and cuda10. I change the cuda10 to cuda9 but still not work
finally I solve this problem by recompile the project

**Comment by ahojnnes** [comment]
Assuming the issue is resolved?

**Comment by ahojnnes** [comment]
Feel free to reopen if the issue still persists.

**Comment by GabbySuwichaya** [comment]
Hi I have the same problem, and still cannot find a way to make COLMAP detect the installed 
CUDA.

**Comment by Power-tile** [comment]
Same. My NVIDIA control panel tells me I have cuda installed, but colmap cannot detect the CUDA.
![image](https://user-images.githubusercontent.com/44731563/88447624-d644ae00-ce67-11ea-98be-94d352a57cfe.png)

In my terminal, running the feature extraction & matching process without declaring explicitly to not use GPU will throw the error of finding 0 CUDA devices. For dense reconstruction, it throws "Configuration has [amount of image used for dense reconstruction] problems" and freezes there.

**Comment by prabh27** [comment]
I face the same issues. I have cuda version 10.2 installed, and I have been using it for training faster rcnn models. However, with colmap, I get an error while dense reconstruction: ERROR: Dense stereo reconstruction requires CUDA, which is not available on your system.

**Comment by quotetoxic** [comment]
Same here...

**Comment by prabh27** [comment]
> nvidia-smi and nvcc --version were giving me different output for the cuda version. 

I removed the older version from the system and added this in the configuration: https://medium.com/@brianhourigan/if-different-cuda-versions-are-shown-by-nvcc-and-nvidia-smi-its-necessarily-not-a-problem-and-311eda26856c

Cuda is detected by colmap now and it is working fine. 

Hope this helps.

**Comment by FiniteObliviate** [comment]
I have recompiled my colmap, and it works.
I guess the reason is that CUDA needs to be installed before compiling colmap. There is two output sentences when I recompile:
`
-- Autodetected CUDA architecture(s):  7.5
-- Enabling CUDA support (version: 10.0, archs: sm_75)
`
Thus, if you don't have CUDA when you compile, colmap would always keep assuming you don't have CUDA (even if you install CUDA afterwards).

**Comment by darthgera123** [comment]
i have cuda installed and then i installed colmap but colmap isnot detecting

**Comment by jackhagley** [comment]
> I'm on a mac High Sierra with NVIDIA GTX 970 and ATI Radeon HD 2600. I have CUDA 10.0 installed and the latest Colmap 3.6-dev.2 when I try to make a dense reconstruction I get the message Dense stereo reconstruction requires CUDA, which is not available on your system. I tried deleting and reinstalling Colmap but it didn't work. I only have one version of CUDA installed.
> what can I do?

I’m running High Sierra with NVIDIA GeForce GTX 1070. CUDA Driver Version: 418.163. I can’t even get COLMAP to open!

"Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libamd.2.dylib
  Referenced from: /Applications/COLMAP.app/Contents/Frameworks/libspqr.2.dylib
  Reason: image not found"
